website/__init__.py
from flask import Flask, Blueprint, render_template


def create_app():
	# instantiate the app
    app = Flask(__name__)

    # register the blueprints
    from .views import views
    app.register_blueprint(views)

    return app

website/views.py
from flask import Flask, render_template, Blueprint, request, redirect, url_for
import numpy as np
import pickle

views = Blueprint('views',__name__)


@views.route('/', methods=['GET', 'POST'])
def index():
	if request.method == 'POST':
		# load the pickle model
		model = pickle.load(open('website/iris_rfc.pkl', 'rb'))

		# convert all the input from the input boxes to floats
		float_features = [float(x) for x in request.form.values()]

		features = [np.array(float_features)]
		prediction = model.predict(features)

		results = f'The flower is predicted to be of {prediction} species.'
		return render_template('index.html',prediction_results=results)

	return render_template('index.html')

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Ml Deployment </title> 
	<link rel="stylesheet" type="text/css" href="static/bootstrap.min.css">
</head>
<body>
	{% block body %}
	
	{% endblock %}

</body>
</html>

website/templates/index.html
{% extends 'base.html' %}

{% block body %}
	<body>
	<div class="container" align="center">
	<h1> Iris Flower Dataset Prediction</h1>
	<form action="{{url_for('views.index')}}" method="POST">	
		<label> Sepal Length: </label>
		<input type="text" name="sepal_length" placeholder="sepal_length"/>
		<br/>
		<label> Sepal Width :</label>
		<input type="text" name="sepal_width" placeholder="sepal_width"/>
		<br/>
		<label> Petal Length: </label>
		<input type="text" name="petal_length" placeholder="petal_length"/>
		<br/>
		<label> Petal Width: </label>
		<input type="text" name="petal_width" placeholder="petal_width"/>
		<br/>

		<button type="submit" class="btn btn-primary"> Predict </button>
		
	</form>	

	{{ prediction_results }}

	</div>
	</body>

{% endblock %}